### ISSUE TITLE
[1.16?] Clients timeout even when they are sending KeepAlive packets

### ISSUE THREAD

**Issue by kory33** [kory33/s2mc-test#21]
Need more info

**Comment by kory33** [comment]
This does not occur in version 1.12.2.

**Comment by kory33** [comment]
It looks like this occurs with `CirclingClient` example too when the client is connected for a very long time.

What's mysterious is that the client is not interrupted when the connection is lost. We need to look closely what has happened to the connection when a timeout occurs.

**Comment by kory33** [comment]
I interrupted a disconnected process and this is what came out:

```
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at scala.runtime.LazyVals$.wait4Notification(LazyVals.scala:89)
        at io.github.kory33.s2mctest.impl.connection.codec.ByteCodecs$Common$.given_ByteCodec_EntityEquipments(ByteCodecs.scala:185)
        at io.github.kory33.s2mctest.impl.connection.codec.ByteCodecs$Common$.given_ByteCodec_EntityEquipments(ByteCodecs.scala:183)
        at io.github.kory33.s2mctest.impl.connection.protocol.PacketIntentCodecCache.given_ByteCodec_EntityEquipment_Array$$anonfun$2(PacketIntentCodecCache.scala:267)
        at io.github.kory33.s2mctest.impl.connection.protocol.PacketIntentCodecCache.given_ByteCodec_EntityEquipment_Array$$anonfun$adapted$1(PacketIntentCodecCache.scala:144)
        at cats.free.Free.step(Free.scala:56)
        at cats.free.Free.foldMap$$anonfun$1(Free.scala:143)
        at cats.data.EitherTMonad.tailRecM$$anonfun$1(EitherT.scala:1155)
        at cats.data.IndexedStateTMonad.tailRecM$$anonfun$3$$anonfun$2(IndexedStateT.scala:440)
        at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:16)
        at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:13)
        at cats.EvalInstances$$anon$1.tailRecM(Eval.scala:370)
        at cats.StackSafeMonad.tailRecM$$anonfun$1(StackSafeMonad.scala:17)
        at cats.Eval$.loop$1(Eval.scala:358)
        at cats.Eval$.cats$Eval$$$evaluate(Eval.scala:363)
        at cats.Eval$FlatMap.value(Eval.scala:284)
        at io.github.kory33.s2mctest.core.connection.codec.interpreters.DecodeFiniteBytesInterpreter$.runProgramOnChunk(DecodeFiniteBytesInterpreter.scala:39)
        at io.github.kory33.s2mctest.core.connection.transport.ProtocolBasedReadTransport.nextPacket$$anonfun$1(ProtocolBasedTransports.scala:78)
        at cats.effect.IOFiber.mapK(IOFiber.scala:1224)
        at cats.effect.IOFiber.succeeded(IOFiber.scala:1032)
        at cats.effect.IOFiber.uncancelableSuccessK(IOFiber.scala:1339)
        at cats.effect.IOFiber.succeeded(IOFiber.scala:1043)
        at cats.effect.IOFiber.uncancelableSuccessK(IOFiber.scala:1339)
        at cats.effect.IOFiber.succeeded(IOFiber.scala:1043)
        at cats.effect.IOFiber.mapK(IOFiber.scala:1236)
        at cats.effect.IOFiber.succeeded(IOFiber.scala:1032)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:235)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1157)
        at cats.effect.IOFiber.run(IOFiber.scala:129)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:306)
```

It is weird that the fiber is doing something other than waiting for a network packet, so this could be a hint
